frutas = ["Maca","uva","tomate"]
print(frutas)
print(frutas[2])
print(len(frutas))
frutas.append("cereja")
frutas.append("acerola")
print(frutas)
print(len(frutas))
print(frutas[2])
print(frutas[-1])
